server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.80.128
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.80.128:3306/ws?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: ws
      password: ws
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 60m
      key-prefix: 'ws:'

